<style>
    * {
        font-family: 'Open Sans', sans-serif;
        font-size:1.1rem;
    }

    html {
        min-height: 100%;
    }

    .addusers a {
        font-size: 0.7rem;
        color: #FAFAFA;
    }

    body {
        min-height: 100%;
        background: url("img/home-bg.jpg") no-repeat center center;
        background-size: cover;
    }

    form {
        padding-top:15%;
        padding-left: 18%;
        width:20%;
        color: #FAFAFA;
        text-shadow: 3px 2px black;
    }

    label {
        margin-top:10px;
        display:block;
        font-weight: 700;
        text-shadow: 2px 2px black;
    }
    label.inline {
        display:inline;
        margin-right:50px;
    }
    input, textarea, select, option {
        background-color: white;
        padding:3px;
        border:1px solid cadetblue;
        border-radius:5px;
        width:300px;
        box-shadow:1px 1px 2px #C0C0C0 inset;
    }

    select {
        margin-top:10px;
    }

    input[type=submit], input[type=reset] {
        width:160px;
        margin:0 auto;
        margin-top: 6%;
        cursor:pointer;
        color:black;
    }

    #content{
        width:800px;
        height:200px;
        padding-left: 0;
        padding-top: 0;
    }
</style>

<body>


<form action="editArticle.php" method="post">



    <label for="tags"> tags </label>
    <input type="text" name="tags" id="tags">

    <label for="title"> Titre de l'article </label>
    <input type="text" name="title" id="title">

    <label for="content"> Votre Article</label>
    <input type="text" name="content" id="content">


    <input type="submit" value="Send"/>

</form>
