

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

    <style>
        * {
            font-family: 'Open Sans', sans-serif;
            font-size:1.2rem;
        }
        body  {


        }

        form {

            padding:10px;
            width:30%;
            margin: 0 auto;
        }
        fieldset {
            padding:0 20px 20px 20px;
            margin-bottom:10px;
            border:1px solid #DF3F3F;
        }
        legend {
            color:#DF3F3F;
            font-weight:bold
        }
        label {
            margin-top:10px;
            display:block;
        }
        label.inline {
            display:inline;
            margin-right:50px;
        }
        input, textarea, select, option {
            background-color:#FFF3F3;
        }
        input, textarea, select {
            padding:3px;
            border:1px solid #F5C5C5;
            border-radius:5px;
            width:350px;
            box-shadow:1px 1px 2px #C0C0C0 inset;
        }
        select {
            margin-top:10px;
        }
        input[type=radio] {
            background-color:transparent;
            border:none;
            width:10px;
        }
        input[type=submit], input[type=reset] {
            width:100px;
            margin-left:60%;
            margin-top: 2%;
            box-shadow:1px 1px 1px #D83F3D;
            cursor:pointer;
        }





    </style>




    <h3>Bonjour <?=$_SESSION["name"]?></h3>


    <a href="logout.php"> <button> Logout</button></a>

