
    <style>
        * {
            font-family: 'Open Sans', sans-serif;
            font-size:1.1rem;
        }

        html {
            min-height: 100%;
        }

        .addusers a {
            font-size: 0.7rem;
            color: #FAFAFA;
        }

        body {
            min-height: 100%;
            background: url("img/registerphoto.jpg") no-repeat center center;
            background-size: cover;
        }

        form {
            padding-top:25%;
            padding-left: 18%;
            width:20%;
            color: #FAFAFA;
            text-shadow: 3px 2px black;
        }


        label {
            margin-top:10px;
            display:block;
            font-weight: 700;
            text-shadow: 1px 1px black;
        }
        label.inline {
            display:inline;
            margin-right:50px;
        }
        input, textarea, select, option {
            background-color: white;
            padding:3px;
            border:1px solid cadetblue;
            border-radius:5px;
            width:300px;
            box-shadow:1px 1px 2px #C0C0C0 inset;
        }

        select {
            margin-top:10px;
        }

        input[type=submit], input[type=reset] {
            width:160px;
            margin:0 auto;
            margin-top: 6%;
            cursor:pointer;
            color:black;

        }



    </style>

<body>


    <form action="register.php" method="post">
        <label for="name"> Votre pseudo :</label>
        <input type="text" name="userName" id="name">
        <label for="password"> Mot de passe :</label>
        <input type="password" name="password" id="password">
        <!--    <label for="password"> Confirmez votre mot de passe :</label>-->
        <!--    <input type="password" name="password" id="password">-->
        <input type="submit" value="Create Account"/>

    </form>
